## Домашнее задание - Библиотека numpy

Подпишите этот блокнот: Дугина Виктория Игоревна. НПМбд-01-21. Выполненное задание загрузите в свой репозиторий «<b>Python_Introduction_2022</b>» в github 

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [13]:
import numpy as np
arr1 = (2.5+1.3)* np.random.random_sample(64) - 1.3
arr1

array([-0.47116126,  0.5435472 , -1.24790587,  1.66694466, -1.00391412,
        1.62457575,  2.06146433,  2.30046873,  1.9546652 ,  1.17269143,
        2.19542033,  1.2761835 ,  0.061413  , -0.44365407, -0.34583555,
       -0.33943714,  0.34270098, -1.23212606,  2.09475536, -0.03768443,
       -1.07537759,  0.12562048,  0.15056073,  0.19547394,  2.33630166,
        1.54030209, -0.98530095,  1.19217144,  1.04625566,  0.77071   ,
        0.40707164, -0.74638659, -1.04610833,  0.45052625,  1.04653085,
       -0.73891881,  1.92140761,  1.0626344 ,  0.58906225,  0.32491213,
        1.68131388,  1.21910143,  0.17795532,  0.17725526, -1.06523149,
        0.08570314,  0.65359625, -1.17810646, -0.90706595,  0.46772192,
        0.00462342,  0.04412745,  0.1456854 ,  2.38429654, -1.10248618,
       -0.32853993, -0.15751405,  0.82276581,  1.60368673, -0.1377994 ,
       -0.59622235,  0.11547249,  1.13102497,  0.30096017])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [37]:
import numpy as np
arr2 = np.arange(1,4)
arr2 = np.tile(arr2, 4)
arr2

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [9]:
import numpy as np
arr3 = np.array([])

for i in range(10):
    a = 2*i+1
    arr3 = np.append(arr3,a)
arr3


array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [23]:
import numpy as np
arr4 = np.zeros((10,10))
line = np.ones(len(arr4[0]))
print(arr4)
print("===============================")
arr4 = np.append(arr4,line)
arr4 = np.insert(arr4,0,line)
arr4 = arr4.reshape(12, 10).transpose()

line = np.ones(len(arr4[0]))
arr4 = np.append(arr4,line)
arr4 = np.insert(arr4,0,line)
arr4 = arr4.reshape(12, 12)
print(arr4)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [36]:
import numpy as np
arr5 = np.zeros((8,8))
for i in range(8):
    for j in range(8):
        arr5[i][j] = (i+j)-2*((i+j)//2)
        
print(arr5)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [41]:
import numpy as np
def f(i,j):
    res = i + j
    return res
arr6 = np.fromfunction(f, (5, 5), dtype=int)
print(arr6)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [58]:
import numpy as np
vec = np.arange(0, 3)
mas = np.arange(1, 7).reshape(3, 2)
mas1 = np.arange(1, 7).reshape(2, 3)

print(np.dot(vec,vec))
print("Вектор на вектор\n========================")
print(np.dot(vec,mas))
print("Вектор на матрицу\n========================")
print(np.dot(mas,mas1))
print("Матрицу на матрицу\n========================")

5
Вектор на вектор
[13 16]
Вектор на матрицу
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
Матрицу на матрицу


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [101]:
import numpy as np
mas = np.arange(0,1,0.05)
mascos = np.array([])
massin = np.array([])
print(len(mas))
for i in range (len(mas)):
    mascos = np.append(mascos,np.cos(mas[i]))

for i in range (len(mas)):
    massin = np.append(massin,np.sin(mas[i]))

mas = np.append(mascos,massin)
print(mascos)
print("Значения косинуса\n========================")
print(massin)
print("Значения синуса\n========================")
print(mas)
print("Объединённый массив\n========================")

20
[1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
 0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
 0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
 0.62160997 0.58168309]
Значения косинуса
[0.         0.04997917 0.09983342 0.14943813 0.19866933 0.24740396
 0.29552021 0.34289781 0.38941834 0.43496553 0.47942554 0.52268723
 0.56464247 0.60518641 0.64421769 0.68163876 0.71735609 0.75128041
 0.78332691 0.8134155 ]
Значения синуса
[1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
 0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
 0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
 0.62160997 0.58168309 0.         0.04997917 0.09983342 0.14943813
 0.19866933 0.24740396 0.29552021 0.34289781 0.38941834 0.43496553
 0.47942554 0.52268723 0.56464247 0.60518641 0.64421769 0.68163876
 0.71735609 0.75128041 0.78332691 0.8134155 ]
Объединённый массив


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [3]:
import numpy as np
A = (3 - (-1)) * np.random.random_sample((3, 5)) - 1
A

array([[-0.54612119,  2.13021911,  2.57060053,  1.84616285,  1.54307296],
       [ 1.10990068,  0.60278786, -0.86378507,  1.53343092,  0.59517869],
       [ 2.57142657,  1.56931131, -0.48975227,  0.70583174, -0.14428276]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [4]:
print(A.sum())
print("Cумма всех элементов\n========================")
print(A.sum(axis=1))
print("Сумма внутри строк\n==========================")
print(A.sum(axis=0))
print("Сумма внутри столбцов\n=======================")
print(A.mean(axis=1))
print("Cреднее значение каждой строки\n========================")
print(A.var(axis=1))
print("Дисперсия каждой строки\n==========================")
print(A.std(axis=1))
print("Стандартное отклонение каждой строки\n=======================")

14.733981924394397
Cумма всех элементов
[7.54393427 2.97751307 4.21253459]
Сумма внутри строк
[3.13520605 4.30231828 1.21706319 4.08542551 1.9939689 ]
Сумма внутри столбцов
[1.50878685 0.59550261 0.84250692]
Cреднее значение каждой строки
[1.1702543  0.65477772 1.25695126]
Дисперсия каждой строки
[1.08178293 0.80918336 1.12113838]
Стандартное отклонение каждой строки


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [5]:
for i in range(len(A)):
    a = A[i].mean()
    b = A[i].std()
    for j in range(len(A[i])):
        A[i][j] = (A[i][j]-a)/b
print(A)

[[-1.89955673e+00  5.74451902e-01  9.81540430e-01  3.11870325e-01
   3.16940758e-02]
 [ 6.35700244e-01  9.00320621e-03 -1.80340791e+00  1.15910478e+00
  -4.00311697e-04]
 [ 1.54211085e+00  6.48273580e-01 -1.18830933e+00 -1.21907497e-01
  -8.80167601e-01]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [6]:
np.sort(A, axis=None)
last = A[:,-1]
print(last)
ind = np.argsort(last) 
print(ind)
res=A[ind]
res

[ 3.16940758e-02 -4.00311697e-04 -8.80167601e-01]
[2 1 0]


array([[ 1.54211085e+00,  6.48273580e-01, -1.18830933e+00,
        -1.21907497e-01, -8.80167601e-01],
       [ 6.35700244e-01,  9.00320621e-03, -1.80340791e+00,
         1.15910478e+00, -4.00311697e-04],
       [-1.89955673e+00,  5.74451902e-01,  9.81540430e-01,
         3.11870325e-01,  3.16940758e-02]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [7]:
B = np.dot(A.transpose(),A)
C = np.dot(A,A.transpose())
print(B, B.shape)
print("Про B\n=======================")
print(C, C.shape)
print("Про C\n=======================")

[[ 6.39053644 -0.08577092 -4.84342329 -0.04356706 -1.41777518]
 [-0.08577092  0.75033468 -0.22273823  0.11056075 -0.55238628]
 [-4.84342329 -0.22273823  5.62778078 -1.63936157  1.07774231]
 [-0.04356706  0.11056075 -1.63936157  1.45564842  0.11671947]
 [-1.41777518 -0.55238628  1.07774231  0.11671947  0.77569968]] (5, 5)
Про B
[[ 5.         -2.61101685 -3.78921413]
 [-2.61101685  5.          2.98821201]
 [-3.78921413  2.98821201  5.        ]] (3, 3)
Про C


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [8]:
len_B = len(B[0])
sum_first_B = sum(B[i][i] for i in range(len_B))
sum_second_B = sum(B[i][len_B-i-1] for i in range(len_B))
print(sum_first_B, sum_second_B)
print("Про B\n=======================")

len_C = len(C[0])
sum_first_C = sum(C[i][i] for i in range(len_C))
sum_second_C = sum(C[i][len_C-i-1] for i in range(len_C))
print(sum_first_C, sum_second_C)
print("Про C\n=======================")

15.000000000000004 3.013351926890882
Про B
15.000000000000004 -2.5784282564209464
Про C


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [18]:
import numpy.linalg as lg 

#print("Детерминант: ",lg.det(A))
print("Ранг: ",lg.matrix_rank(A))
#sob_A,vec_A = lg.eig(A)
#print("Спектр: ",sob_A)
print("Про A,она не квадратная - проблемы\n=======================")

print("Детерминант: ",lg.det(B))
print("Ранг: ",lg.matrix_rank(B))
sob_B,vec_B = lg.eig(B)
print("Спектр: ",sob_B)
print("Про B\n=======================")

print("Детерминант: ",lg.det(C))
print("Ранг: ",lg.matrix_rank(C))
sob_C,vec_C = lg.eig(C)
print("Спектр: ",sob_C)
print("Про C\n=======================")

Ранг:  3
Про A,она не квадратная - проблемы
Детерминант:  -5.316513377982711e-32
Ранг:  3
Спектр:  [ 1.12858308e+01  2.54353340e+00  1.17063579e+00  5.52785301e-16
 -1.44143566e-16]
Про B
Детерминант:  33.6041393387198
Ранг:  3
Спектр:  [11.28583081  1.17063579  2.5435334 ]
Про C


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [28]:
import numpy as np
np.random.seed(1032217618)
print("Варинат:"+str(np.random.randint(10)))

d = [0.1, 0.01, 0.001]

def f(x):
    return (2*x-1)/(2*x+1)

x1 = np.append(np.arange(0,2,d[0]),2)
x2 = np.append(np.arange(0,2,d[1]),2)
x3 = np.append(np.arange(0,2,d[2]),2)

print("Метод прямоугольника\n")

I1 = d[0]*np.sum(f(x1))
I2 = d[1]*np.sum(f(x2))
I3 = d[2]*np.sum(f(x3))

print(I1,I2,I3)

print("Метод трапеции\n")

I1 = d[0]/2*(f(x1[0])+2*np.sum(f(x1[1:-1]))+f(x1[-1]))
I2 = d[1]/2*(f(x2[0])+2*np.sum(f(x2[1:-1]))+f(x2[-1]))
I3 = d[2]/2*(f(x3[0])+2*np.sum(f(x3[1:-1]))+f(x3[-1]))

print(I1,I2,I3)

print("Метод по правилу Симпсона\n")

I1 = d[0]/3*(f(x1[0])+ 2*np.sum(f(x1[1:-3:2])) + 4*np.sum(f(x1[2:-2:2]))+f(x1[-1]))
I2 = d[1]/3*(f(x2[0])+ 2*np.sum(f(x2[1:-3:2])) + 4*np.sum(f(x2[2:-2:2]))+f(x1[-1]))
I3 = d[2]/3*(f(x3[0])+ 2*np.sum(f(x3[1:-3:2])) + 4*np.sum(f(x3[2:-2:2]))+f(x1[-1]))

print(I1,I2,I3)

Варинат:9
Метод прямоугольника

0.36737515557982653 0.3885300888968458 0.3903617675660328
Метод трапеции

0.3873751555798265 0.39053008889684576 0.3905617675660328
Метод по правилу Симпсона

0.3586815446211058 0.3878421383855406 0.3902948876093821
